[workspace]
resolver = "2"
members = [
  "crates/*",
  "polarway-grpc",
  "polarway-sources",
  "polarway-distributed",
]
default-members = [
  "crates/*",
  "polarway-grpc",
  "polarway-sources",
  "polarway-distributed",
]

[workspace.package]
version = "0.52.0"
authors = ["Ritchie Vink <ritchie46@gmail.com>"]
edition = "2024"
homepage = "https://www.pola.rs/"
license = "MIT"
repository = "https://github.com/pola-rs/polars"
